name: Testing TypeScript Actions
description: A GitHub Action that sleeps for a specified number of milliseconds.
author: kjanat

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  milliseconds:
    description: The number of milliseconds to sleep
    required: true
    default: '1000'

# Define your outputs here.
outputs:
  time:
    description: The time slept in milliseconds

runs:
  using: node20
  main: dist/index.js
